---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBbRmY2pbxLdbLggkFp1D7IAbjnUoTZvXopvw7BW0CV65AQaOOK6WX2P5xcTsQskB2/vTGvX6g+Qm5/lBWcTBGyMSqkXa9IiyVYhQJTeggOPw8Pelofq6Eek4pZumY2yidP8f4zQnKZJ9HgwErFvS3/IzsebjKQTzvLy6o1f/KlbAl035hjq6RG43K36D0VIkUAfxIlEeagfPOQh7ICcfHggqiLoK8H5CK+cp1Aa5Mq2yHSf+YaggvEZzty9IZvhb5CeoELQprrOF8HUkTomFzFKtxw5xSa/C+EJpwKGQWO/YSQZnmEt7metBu5q5wuWDzx09sACUfWurnH1qnxf5XWOwy7Bf1YH3KlGqPrmXEr6mXXUUhUvOhOAGFtfFVmd9ajwsuXWPp9c7kCDroSfpE2DXcxFNO5yMc3d6SwQG2URNqnrFHhg0MXHJ84RsnL34OBePOZj0i78FNrlfkt/TuBK+6airNk4nNMK9bWmUqEr87NXNtaOtn9ntoNmoeCIlsLXYmsyZ44AIftlMrGS9nY5Qoz2UitxPfrRwahE8Uu5EtsZB4qz/C+KTv4hFVtO84v3CZ8RJT08v3NDKeLd3jjE5rZJGyqEcRJ+EfOyKoILEz+v0ZijYXoWA4AcAQ6u60ysv3P5lukMQl/JCjTSY1FpEwfi6t2jbsfBypLjhujRtui3R/tSCzwar22eIsroNeuhD+N9xkc53mEWHI=
    admin-user: AgARF/ebJoS8yBGNYdsDIju4m5iyttXBIrb6BzHWBQBc5uJvdQSyJAcSgSyEIZ74H++W74LTAZfE6DqP6Nhlmj1BrA0FG5QCGs7s0ff9oIKX/pRrOqRwHAsU2PuhveyDbwh1lSu8bAWGEs65rQ1swN0G2DMuiliscnn/rqyXJYAeYU2aVETrphawtl4fw64Yx7s6UttsbyjMmEE1uWAL82XHWvJqe9ABSxR1g7yQYtkVVla1MReP8SgIDUoq2ttGm81HzQRPS0XvQnoDCyjyFIXw3prxOm/m3F7YGA5bcM5CWr89BpAhDlvObQ8YXjFA5SOnvEiLmtS6KcnY38z6XfB3DNTvh18y+EQU/boxW36wzOoZf8JQfGC6st5BeZgy2H6vj5ZO5fYc09Twz2pkWJo+06Dj+SqFzLDb2EJcI5JmD5eCWor6oN4W57vJX/moa/xgMpYFtkRVDRufInDGibRaBqCrp1bluG4jDRw7mxqDF/NIRpvnbBzkyHMc4qfFLaU2HNSjWXcZpQMaL5/tgaFIuN2okdjxt92q/y++jn1VMmKoCUcWPTNPHNmgIlw8GeM9gd7DCoSAF61Ruo6JT5SXpLZc4r9Xf68v2AXsnWq9gsHiSaSuT9SZYS7wYPgpJk5yMwDb6mbGDJ6suopujzP4kx5jgCGn2U8MxbZ2kM/BAIqqwMmdnHGhrG9dhtzq4vArhOsGZw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
