---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    TUNNEL_TOKEN: AgCwoZlnjJR0ZqWKF18LZ6RXaeYX3HqghYpAwyBN1DFAalpXzHP+YM/3InVxxPAYBrbx1VODbZtGWETLisFcm64QHcZYtswf4OPvUnqjApQSyVCNOVDJhvrvgRS2TUeEQg/GoXe4yrddDN6dsrmmcIP26Mi+Z2LnNF+ZySUPnf9mKcgjcGrLXbi348KWPvyVnwidM30UH6e7G2DjotJ+7jopcEVeCjbbj9ckOcGdi+Xj6F/+dQPpfAKtDh/AenFVkqSiGHcSUGtDZNVWgrx7nWBgQXdPzOmUD4xVbUfvHGj1Mx3npBXP51YRNoEdkR5BFLRPw+K7FIgjOLEAYozpicwCrJAjAk2Hg326Rk/lCQOZ107VgxVfqBg7kd0c5Gh/vX1qS+5VS2XEYI/N7HZMqMi79funyre3VuPkCDuhstZvZ5Q+5LiPDVnq6y5qpLo2d//DgHYWQq8SivD+p2b6USUH1WgUsof44F0JmvYnwMEDR8a1iiW1oYiZu8j2DXdiOQKKcocHdr+J4SIPIzvovXcWGA0PmWU+g7kAnzJ/MOw52X/GNMJW/nuxnhTXM+0VrtgbhFsgIVKGqP+5btoQXj8YpTfdTaM6i8zt90z89VgjjcztMZh1z9QeP4qvnbOiNQ+DkwDmmPZgKjsUAnWsT9P/3BqPF2gSVxQtqdHE9RPRtjkBu55uAGO8JMAw9q+9N/BwuMmOOmzuaUxVefImEgjMW2FBj2HRMaMQqpnFnb+Se0mBQTSmjAqjCDChraJAO9kQNRXvzPj/YawAe8PLctM4TIfsLyvfHWGQySNQJfAz9qM3VLHDLDbxwdGdsC1jY4xiQZEnhcbS/rRxM708Ad/k5U0lGTT+zFP6I1hPuMPjNwDzjFcKuW6wHeeeI2066l2eAwWTgo+oGF9RlVAOb8bh8ziQDEDjz4v10QmDZdYxkFaJaEU=
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflared
