---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCpn8nQW7cx6MKOP7k0Kg5Bx9ATg+n7RglgUU70oS645Qu9IalSk2LZJnUe8Q2aXpmOmiVNTRULIFhQqtmQUJuR6Rj58ReHnAut0/MH66RVMXdk1nTF2NUXIk1jk+CqEVLFIMVaRngeoVvvWk2T6DJFD48GfBkQkKIF2rMgtly2tMB5UX2Od12l0FB++NPBmSM8XwZQpZNAqUzGn/ERBMXrikcabjN2y/Br9bBVpe/pu1lqTzJiJCdo39X654CAk7e0GHQhY1J8BuEAKQ5qI6oqM8gYS0I1pnAfwrLSKg1I2WJINIggl6iF6fsOMQFybMeV+K582lRyFFwVJpHH8SLJfFLOnlFb4LvBKnLK+1sKOh07utQ561wMr5CTkpT/d3VkYhm+Qvq97pTAE1B8JB42+k56MbrAD94QhwFumGWWT1O/bOseXa5btDP3mokxeYD5I23YQGbuP59jtwAKSkR5hMv2eJ+Y/WayotZeHA8fUAulmCTQE2ujQO+dvJagFqe1Qr3/BMsmU0lOBIh0/nLpK0REjk1d6862xCDNiVkpeH/6IrOw3mwTwEb/GSPghRkQ6CQe871w/8qATTF2d0IPtIFK+FdAeNpViW95Q0tpH94F2mfzbF1Cv/mr1Apua2W526Yx81fhOJOntbDhaZTpcmF4qPkmTKpYKXSdRozk7OpSq42ACNZ6c+nWbK/VGFMe1zBV7b+StI1qUJ3trm4zrjDnliNm3j1XY0uGkD7JikZQsiOJqTD+etfpC3RXs51B/ZIR4zz6zq3eNyM8aAXOP+akuTgjWO+xdZVuchlcrjfHJaI+xl2AGIK7XiNSPAr13oPWfOLY8SvtxByxX34LeSd1osNqZcoWwiyJgdFQEzbwRmZIL5IqXGaKBEg3fkbPzKwVHhB+xi8JAzvYnEg4kCcnBHwp8EYTfkdx7CIokWhW2HY=
  template:
    metadata:
      name: cloudflared-tunnel-token
      namespace: cloudflared
