---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgABH6G7ZPFaJm0TM4WutDm2yvTYlUjPath/0EeTF45j4Sr3ky2S65mUhujlOjlizEcM5ftaiK5cwvWJmvCIS3v39qemMq73awC+7/vHJVD63Weg/oQ34FGJIrQuXxHrtbUX66MxmBZzv6vljHN+8nIAb7pf0ZWOr3m+1YFDvSeEpozxx+Hzn2cej1NrLqami6HUpY4nm6wAnuRrdZDiPnwalbc5g69M+Egago+JNqBY6XbJpAlWQlWa3MxKqBbT2tEwyUorVNS8cklveojKv8rscnoVzItTl/D6TjriDSvMbCzhQ7+mtxsxJPWD35DiGv6zYzybp6JiSVwaitTFdiicJs32kCyFaT9vxkR1Le6a/++qLp3b6noATlTmUJea8JC1K5H7He0TKB4ZftM6sx8zB48q/ul8fMI+BLmqQPYZz6J06CSR+AMYJ6mqOpzGbayzSmU3n7hbyAs5JtrMqGDAgdsHMeCOm0adQy5ZEuQU8WaH72mWvY7/2+SVGWU4bSUfv9a2wxh7cK4RQSt04ng/gxNQhUIwAmMGV7ay8coqSgG88YslYAZdws8i1M9hfMBEEYvdmUlHQVZXxMRCQ6N3tKWunJlOlzDmxKGYQgCP0xjq8n+poBPzWMMKN9fD41cKrsGJKx2ajLTXgRTujHRikv7SHGm08VIQfFJJbP2WvoeFHaGazx+yf183haeGxUPkwHyNzATzw0xsrNtXmgZtj4dFrBg1MzdmIFOw6mK16z3wZknmwrSqrg391iUIn3aeeo99/LrAkcoR8NyPYpudsrXLSvWw2aNBIyfpGZ2PAdXy9GnpTMgAhknexZUXhHuxhQ3Uzo2QISR/lIESu9+2KMbwecgYv6/B
  template:
    metadata:
      name: discord-webhook
      namespace: monitoring
