crds:
  enabled: true
  keep: true

prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 20GB
    resources:
      requests:
        memory: 2Gi
        cpu: 200m
      limits:
        memory: 4Gi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 25Gi

alertmanager:
  alertmanagerSpec:
    secrets:
      - discord-webhook
  config:
    route:
      receiver: discord
    receivers:
      - name: 'null'
      - name: discord
        discord_configs:
          - webhook_url_file: /etc/alertmanager/secrets/discord-webhook/DISCORD_WEBHOOK
            send_resolved: true
