---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-token
  namespace: overlap
spec:
  encryptedData:
    DISCORD_TOKEN: AgArBZAAfYCUQ2WGhR4fcF2hxFneCb0LJocmiyL77jozVGG8DJ548yK9MVaRlJW/w+rmquxyMT/ojCFKZWg8YL8whA2UD1soUp0OERHkYRPc+dVccGEUVf0VTqbOdCHBnKNkfzfht/xL7/6J++nu4AINKUGs6cPR7zCkI2LVEYDkcT5NHnqKLh0z6kRSHPlv4hYAyK1haJwnCncEuekOuTlB6iHLvd7JM7HxrJVL+2uGxQwqp6C7zOERzMoxjmTjL5U3UfOmhbJRLxv3r03bUP2n2M2vY7J3/oapMc82OLuVJgkhdfZ6e13v0t279VSrgAdY6M9n8OAVvDfcFAsipOK1Q45xEX3mYi93FJBAtueBzvKgpicx8i5yZTZexqJx+6wqbplXtrONy8xd0EX9HRiJHMwBdlWSEu0wlEEGFgMOIyaoxxEb22BXAjTQTzV2DO825T9CrXYeqXH117paPUTFg/3Y3i6gppxIicOi1zsLLa+hxWnjqkZrkJvBexYm0bnwZRvFPMG4Bglkx04OCU463QBpHJmPb7F/6RWd6+JqOvuhg8GmgaV48/8EDnUhDIkXiba+EN6TLJYDa+yKvGaodYeWmdlEAagPL4Tip5S0n7zVkODEEY7yOAbVxzPtorMqkmaI+y8mzQRo3jY+4ote+6jCeYr+o7N+jZneYZrlJVyLKQ5UQfRGigFCcJbBVktqV/FJZRUy2WculYvdGycm3/E+NWTSwd2PX5xxR7emFUqe7SpA5rzdoEIZ22nmLB9cYveBITkIFsPp6QEKkvma9frrko/fOuo=
  template:
    metadata:
      name: discord-token
      namespace: overlap
