---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overlap-secrets
  namespace: overlap
spec:
  encryptedData:
    DISCORD_TOKEN: AgBDn+Mkz3bXyWNYe67JwvFOV6PIjcpnr4quj1VwN5piFJgk+uowb3k1+omRiMwsY4kzySU0rChDH33fb8FGIyTEVQCjZQSVgDAdj/AKwMxECMNenlb4YsOJzpcjpVVpwia0iB7EPoyfmX7aQUrbfgGLoyRtAsjdF0cDNJudmJD/nTQUMZ/Rjyt9QhMp6Bt6hcJ2ldPIMK0sGzmbgtPo85Yw07gk8doLDW+MAAZ37ju4foryF9c4SzObTrpytUJEo3CB7lCWypOAWYBXajurFuOF1MlbRIKE63qmLlKJh6UGiJHes1zRZEilcns1TXm+0AGVosx7bO1FY0iZx5Hwoz2930P5biPdEnhUcHIArqA0NiRse+Eq2btlcMLNJ6rhoNssW8Wqk3J2i6S4U2ne1sprKIC7I7kSI1FeaY8EMx0l2nsGm2IaDd4VtwKqivOhdDkctPYX8RGsUH99wKrlo3h8DQnnWx8yZ9VX30G+QlJIrJZe9seEhG0C8G1J2B4ojZgkPZYrOYEIuFizrniKIu8tF1G6WKkqsWFjqdZAiJCaa482IWczji230bKz9z+iosGrBvxKQi5Et8Lg9ib7A7ytF0kfvsfIvqdhKU1LZuSTq0+EwOQ968XL5Lf0WJQkwZblRQYRcpJOE2Ql69cLi2qk8Ff+ou9qi17waiN/J2QxWb6WdJ3+kkjmlzUMrL2PwhoqaL9PTlwpevarprOyQlBGBmXmBhk0u1slEihNKumxFVAKaD3PXoGiAzltz6OmMxrOzkUHb7NuIPbUxPzR6o/uq1g4jsdi8Sg=
  template:
    metadata:
      name: overlap-secrets
      namespace: overlap
