apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - discord-token-sealedsecret.yaml
  - overlap-premium-deploy-key-sealedsecret.yaml
  - migration-job.yaml
  - deployment-bot.yaml
  - deployment-web.yaml
  - service-web.yaml
