apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - discord-token-sealedsecret.yaml
  - overlap-premium-deploy-key-sealedsecret.yaml
  - deployment.yaml
