---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overlap-db-role
  namespace: overlap
spec:
  encryptedData:
    password: AgASVoxBfN6f4NN0wlNJw9lwFYjhb4KylqId/raOg0fp76vkNorcM1WY0U1xjMya6pHCuwM9JlQZXMA7nvaP+juxAdZtS66GysevKZtusfGfQB3XDo8zb3hfd3rRFHMl6AX2dE9LBtFym1T/QOnORMQDxnwlP+JU7gCrOYrcL9xYGayymyRt5ZFT+WTN3OxoJZIq+91AhBUuWIg2dkwYePH+slVJ13y5TIKhdY4+iFmfsK6K+CWa293qGOePN2Xd3Ti/eq2W+YHI2H7uMWHZnc2/XIhSUifN00lvCbrhe6BTxx9o8ngGSTpJWJAxD+52ipFRsAgN40QsH1z8K57kFQVr5XMb9T4rUnO14k/c+0jis2S7T8FPtnsoK71WxWon4wHW/9pR5zKKVDDK+9WDt0TzAvavDT2aDwRrTvvNcuOAIG1mxARtEmdzZcuPVZRCXV/+zIn6syGq+9S7/veaCv7fH8TkZdn0tKSGliAHwbJkZJjPLRSk1BL9p8F8/cAq+Awl1QwyGumj5+WKKldE8ZVk31JtamuDnOj5/slQKNDYcJ/nifnLBDqrVUXklw6eCDDK86Zk5mM9/76A4AgvjT7dLSlb4crRRuIyc4BH4yksTLN7NA9SymarkoGjWKnqMxxTHDtz92ZnxrzvAsq2QoyyliXqW21WBSCeOd4HETsYXIpziGCDbkqN6EfsdN++Pj4BfRmUaq+iQTqw3byegUvF2K72STf2u+mFClR8
    username: AgC8HpATguyMBqlu4aPTEkrSTzgOlSlUTJHU9wZllrEUV4sFpMPSpgotF4JSBQkq+qTuSL0OALm/7VgPpvCTOJcyBKYl/XAncQLf4yfHuwBvSoHMlwc4uF/k31sj8tTlvd5X8h4dB5sJo2oWYfrAkAHP/kcMdmBKy50uZ4/frY4i9/eBe0YX8TaU8SDRTLV29R8b2Fnyj7aebP6A4fqwpOz2nzdLuBC0q5dBGvekYVrZCGcGiLarhFhIH97sYxRDYgkNVY/MKOf7tHBny0bjIRjIktZ7DU3zsxKG/XT/rsjMhoYDcc4tVTtdPY2KT8EvJy9qm6l1x+dCQQtzscBFb4S87Zj6aLNQ4V+enVpsQWxZo4UIAIOQYKgOAkqqBiscDnbogSRiTdk3UhZ0s2CuJCB3+nYIIHbRluwj3f1FsnkfsMYMEipGY9KsSPQFzVFxJsm3TNyRQTKdJj1v+pP3CGOjbSGUrlWLM/6e2DwwTKLg6bkK3OiyocT3770eJBOCyPKX9qxZrYM6oFz08tvkD/4FPYQjU4AWxUnFouPaM8r0FrBEsv4JP5oiB/4zHcFQbiyzk3BGDwZs95euGmNILv0/PehsgpKjnk3gK5WlFhk3GGJrPTGOEo3NA4QSR8IrKg0ShooEAJ7GVgHATo8/1Z3gdCRS3wCAs8St7WpGkCpDECMraLl4yGOJll32KdeJ63k1leOX9gx/
  template:
    metadata:
      name: overlap-db-role
      namespace: overlap
    type: kubernetes.io/basic-auth
