---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overlap-premium-deploy-key
  namespace: overlap
spec:
  encryptedData:
    .dockerconfigjson: AgCYi2sxMmNRJk0Sb0UiS4hdSVBdFfJg9kfgXIiWMnqjSr4t7rGU4lbKZT7V3dBGutbr14Km/xRTTeeihkIKCTBMTWORCOlWE9DSJ95IrzEhVLUl8tZvGTa4nPMVrzC8QB7/HfCttOybbrNx2xa861Q+ej2Z2p53p1dQ3/IDe4rSX5i6cqeYGe4dzOKKMkmZmU87eEHPkMKVVBv1kUUxxSOeqCHqHblluy0+Oo5Q2VxSptKHPKwnv5KKqlw8qBwpDx/5C2SANvPcuQpqYsadC2jLj+n1c+8cBJiF+XpjAfqkD3+GZMpxFfoMqYoqImhLC8+rvICL++kkNVf+eQCmds/9D6vZujkWskE7AeKCqkGbp/Jre/DkclKuUpftjgNnriVzUHAjUlubtGqQjgvWcI1WUCbDXwNDIY/Z1JJX/mCQ5X3J9UpHmuTIsB5LtqIG3IkQVI8zLLGaxB/Fomwn8nfr/3OswOLPkSqefgqS+5s3X6qC10kzayY7KuWDhM+J5+znwvpSqfYetmGDOyEbXiInInlmxluco2kzNI82UT8sxo4G4O/aEKK+tdEmtuSPrEct76+sDu/erCgAcroaIYlqOzMB6iWQPykXrvv9eBkDileXSwqbfcOClpY3s2E6+TeNpN7d8A9UJDTb7ECHLJ4sIg087qyDpW9wTYox6TG8SuBq75G0TFcHGXBgdKDC6BuFM1MdceLQrRnZ/OisTb5blgoOefTW8ebX8OxaQJocVehYRz6DFtL45HwPV0ov/X1pFjSh/px5H1P0fWiqM+1JxwGVLD9Ohfan/JxBfvZuncWMDBUNGtbWgjb47lQFovF9TF4lVK28ysFTV5awC76hgucCLle2nURtBhUtfd+Ovjcy4RC4xGTJ9ngzAd4u0Lx7u817uHPmpHVuVWKV22pE3w/MdZf5RW7vt5ZLItUK+bYLwtpX6jzX+po7Xjdfo/I=
  template:
    metadata:
      name: overlap-premium-deploy-key
      namespace: overlap
    type: kubernetes.io/dockerconfigjson
