---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overlap-premium-deploy-key
  namespace: overlap
spec:
  encryptedData:
    .dockerconfigjson: AgAHjb4zyA4c0OtENGN18wuuw5KPxDWicfXDv59MWT6i2lvPzStCquvL3l4nBT82BgiAMjTQKLcTSlvBRkJGvRJDcOhMoJxI/njY3eQfS80Ec4uz/ykzvV2B4E4fFBg8CizIJ6+MJhFuOA1O/9UjGr7/4i9vLqhFImFRM+Konpp6IQp96XyOkpt5CZIBdVPaUVQB8B768aoJMrhX68AAb2nr9zW1HPBinn0wIrv7EISpy5weIUNpKPTpvkCF9QipLEcKQoIUDuqotk0+5ofdk0if2/IlR3LmCkbS6LD7lTjPm5h2OUq2B91a/+Pp+DQ+vAEH4Vx+EcDI7TjN9kwf+w/t2IMA1VIp8qu4zgt5WSMK7piX1uDIVHzsa3Hvt78WZkkvHr9nqKEwprbaMBz5FYFXIx9Rize1Li3wp6ynYHBL2Q8AktC/dwDqQQr+GQwc/+gKfhvW7AHpRBsaJirJrmtt/5erlZytBh3eLQRoIt1oXTUxz/UXnwD6/pp/kB3PSMZk/Qt37DjILU6T67D2kqbMVxFd20SOlFsgIgEO3rY2v7eSE51w8ADkQ4T5yIMW8htIzv6o+3iKkCeATuePeyNS6TtrgrJeQl4b8PiJtWkK0+FZwDBSjvQzEJDU3NsLsO0ohj0Y69Upvr85SEII42k5ObhLwGnPgJouYjtZVp2eP97gPNQHbmj2IuJN8pEnH0A29NCISAmwsey6KUcuEroPOdrJZR1pNi+pBfil5LTAlapVReYeVlDFNDA2X7Yo4w1cke9OUh4oO2VTdPjV+S+l3qBhQu4nn2dVbwsuWTN70K7ileiL158hjdSimJOIL41oP3rt/jVizlxpqB5Y/xruL34jYiQt9rWT75ZHPINaqwaJLe57jyZrEBrQtvRWr4PRLMuiq+YLBz+2wr6oEGv2VuWf/SDpZffmIY1oZ0zmnamLV343QE0wlgqakXeGRWfV2jsBjCKAdjeYN+9H8/gmkuLTXewncuCW9CB3aC5xIXvMs9HA2c26YlF+idx8sGB5JCPMwpvLkDnYRpih8y8F69GzZbfduQJOUUZFr4b5F9sRX1cIIixoPIYLfE75l72HrWperuXpCvwN73dQ1nt+N0avgh1+pyWF8QF56w==
  template:
    metadata:
      name: overlap-premium-deploy-key
      namespace: overlap
    type: kubernetes.io/dockerconfigjson
