---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: overlap-db-role
  namespace: overlap
spec:
  encryptedData:
    password: AgAMdE9FJ5aluRKjy6DIK+IurrjBSUEp1VmkRC/R7xcBln55PEI15ljB+0souQfzmZDl8A48rhSqtXP7aiulECCPIUIUXklSKWEHx3dmjvF92c/rcx4VEfbwt7fmoKoAnbrBeOTuSc1gAp9M9NdEiHl94WcHkV3MncC4uG8gYYdvadMxYtppK1MAaTD75EH3OInYdCvN/oQMxzm7CQhuYOLXSPsCzgvcEWUH0PB/Yckyq1xbu4QCdDjn6jNskPEgGWqTijxWElMnHv1Dyug9NsxbcbjFbn33njJT3vVFi48gkmwCoROvLw3/gj7vHoVrAC6BwBpF/WSE0pyrqdP3KJ9dYLswpUsqgWuQvlhLSkUTYcIdHEDPsUMU0s/73CBAxHfKa4xXuR+z9BNy+v8Q7XwVNAFvadoAFTywKrRh/yanNQzqeZKpxNsZh7ScvCrfUBUveDohxSILCxKkBTAVbCkFN3/xfsJf35PH0epxHMF9x2fmNiBzH/MSsDUKcopOEszPEWkeuLb7AvaMPA28oRvCwgaGxf+91Vm7rKTMLuzz414alpMl8/0mI5omBBY2t5JOGkKK6+4cTpnnzV6OdP14akb8SuJqRozf0cdwIrlg5dqgF9lZRvd0/ujzMLpUEQ+vincD+m+fFMI1zWuryjTAqJ9q0GLUF1L7z0j32EHTuTjBI7l4GqCA5W5ONZFDPkkQfKYEWsUmyB9DoYgos6Cd+SXsnOd2H5T7nWSX
    username: AgC7icEh79Aiypzs9RNd1yk8I/RREF3js5toxuNZj1C58AFreySzZActTxaRpaVcuZvmwPEL4SvOcz+FQGvKdFuKE/s9tfTOgQNcZZ9YrvENT/I4IVbLtwBG3/yUUjKRyZMYJCtUNmgGRCJgYFP7v5TmR/sYBg8ORIuImaeJQup4FJZ91kzbe1Be1stawKXU+muyLUwpdSJN6zlZ8BOuaNZ1ncb/yDOuKQqiZVsuPzhNIVlZ4Rltp1llgH4BZtMOrdZrVZPs33w3NOdMub9y8wZoE7OF7f1U2AT2r/G2PhCM7idxiZLT2s5kON1gbyNq2tdXqZSifDRuXzOjN4QagPenSUbDF3k02MrLQtAAQgrWbd3pXyo6WrrZEqSq96aVETWYUZUMvRpoloC/7NM6+N6oZJ2vMpBZ5JvlQEvTNUcWtJ6zddL903khumqkUFopP//nk1Qm6/iwEKRFtpNP9BWDUrJNOmYCdLoUGaDrKQ2rGeVlUBvXUNonAqeuqy3wunLckWoBbkn7pQ27POBg6qAjrWWFv7mSFoEL4HRqDds0jxWGGJWM9GSyFQpNoosAGUNxRVdT65yEfSFiVHmXiDF6T8kO6f75LiObb9XncbPJ+y86YsCCfKBW6wZvQ2hCU/RsdlGAt+EtnY68lWSZMCCSB5cWonuZTrVs/rXdb1fQq/AwumNxPPYbzpZpJdKplXkCUWP+XV8=
  template:
    metadata:
      name: overlap-db-role
      namespace: overlap
    type: kubernetes.io/basic-auth
