---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgA6SMPC5S9eyh1BOS5stE8D3P2/H1m3YSo9oLbdqQ+D5plJ4PwSdyJbRQY28Q66sGV2BceigTT9avK6g61c6swpHz77wRQDGd8U5mBfs42hz73UhmhT9Qvv/3T5eadZm1yWbfN9I/wYaYZ923oWLajBGH+3+w41yAkf9Lp1sEDCCjvaAg8rJQGUm9phARGe1ggRKI7dRgL7ViUO2irmnI07JKYb04y/ChNV13IFZGX5wJCOM3zQCB1bsC8kL/e0mu3j5HynNdDWqBIi9Dkdc3CD42CwDiPfyK1JTYgQwchlb1NcoalwTq8SV9Z19ldiT8XvwPp1vE1hAMxnxsKPItKIiwmqi86BIHpeduFfil5N0uQZpqh6fUEDMPuCGTeAwbN61nWjxu0WVFVr8IrU7Ifnf69xJqReQmMXE2RekHckj6ixXGcr5fNoTHqaNCwnSiK1x5fUZqF6L54fftb/laijZksZy8+7zMPwNf3Pvp3fx9d1Am97aCy4qj1XBPlw4iM3R+Ons8w//Nfuq8rLa0N9Kwvzy+cuXNeutAj1wuhJUNi2O8+PdaN7D0gvaZVJimX9Yw0GTz6MuOMlvKJSv1Jm7S2vvv1pqP90jjYt874Vqh3XNcUCFJFJ25LgVYfqcV2PnF9N9wpDJMAqZaSFc7wjyDFopAXu4imBXOPrFAXp2XFyZravVkTlDOhvqlre/JKGawf39+N2uIJCaZ6MLBCkqg==
    client_secret: AgBUu5do4dc+yRt7m7y0Vz8nwTis9uG5EaS9lrM481mWqq2GxyLZ184rOJG+d6mZ3iZTWY6eWEAhNYpx8rVOYKdfqUj5aizCtxCIj4r0dimWFQDRfikw8vMjTdshURYHPj/jHlaf1K++96o0QVP/Bvt8RBt5HWbGC7yEAkXaj481tPWewfwolzBFQGA9wHsT4PDsOoSPTiW5ZqkbI+k/CTvi1HBmZXb8yeUkxrOaX2AwU9s5Qkr46ZuROzn/gpPtxfW0cO1B6nInPsZRCoqNwbCFJGQCFbqVMRhOKZApoLTEqgOpWM7SQNmFieSiDzGT0RGYTYNKBT6SB2cCj1BAOP979kPOVYa8z4kTyktKEyqqcktZ2mvZUupXeGZCqp++Nbuv/hDpTp9MfU1L+nI3o+9s8DSTcVC2h06xzJ6ohtGAaoEy4uL341xHBb+J9T201JCm8x2YJQpJVRl9CXac85BTLQ+RrnRFGJIxN7NX50pDrdy3KwlUDmzETEQug/3Jame5HhQ24fKZ+S+vHc6ym5c94M+ls3XSmRIXqfGOIfSvisbgE8DTyRLJfDvHThjaJdxTTLFYIHVL/5tY86ou9prAq9wWVfrmGNpOk9tZ5e//ND810EZbI2Z7eE+TUbwq3JjuwjFv+N02ABn0usm4mWbyYMAtdcCUEnns0k2Dakaa1BzjAR718siHkG1LoKd4BuwbjQrjVoImkVdxysnuYUe/0RLeCHSkwsZRN5jsJUQ7I9XSuh/4yl30EmxWYOuprUhfFyTWvvgbnKY3mXyMNLo=
  template:
    metadata:
      name: operator-oauth
      namespace: tailscale
