---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: loki-s3-creds
  namespace: monitoring
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAKN94nM/fpnwVdgElmPKRFCaZTbbgUwWRwcbn4rhFUslCsygKypRKfi/HbUsf6yfKk1GP9dR1OlFX3Uu5uVOmOWExvtpfdyBt1AU8jxzuBakr+s04J7QxGVHMox57PYLhHIheKK8h4wBpgTyRqO+sSpc+RnYYgMEqHuwK8M5j7e3Cl+/pIS/guaVjpDuvPACKW3aSLSILFR/ktprBzGhzUe1707Wz+LnfsDhJ/C9Odeh+c83mx0qNtVhCTWOVIKseqyzLe86V8cHa4EmjtV1lnPo8fnQsjzZbYp5KdtKQvxHv6zxYmNiZwPcX3iZCYwV7FDl3EtIgrZZNdT9WBMURXrRM9kqB2cck3ULMZw+smFv0afrZXZkIzQKIY4+cgKsbFLBF1RJeKLwT818bt+n1TlMwXcI+nYliEQWN8b4dmkUEx2Jybn9ZD0fFnSGjey5isi0Y43Y/DSn6YIhcF4ehvZq9WwiZWQSEseOCV0JLPtqXa26FfWJON3YRy97U4h4UxvVykuv01/a01PqcIvlWQekNnshjrK8nAR7INjjK0r7y8WAmQ+DdOtYCfv+4DWBvYqfvcX9f8LEAr4k2fggwgcfycHUPN2usznZWT9l6bM6z2NdweSLVZDqfF0fYsqrx2MnRAso9E15uzyAR3aCZrEo/hshV9aJupaFtVM5XZGEO3nm04fyQoC6QgrCEylrmuUJi6pnWyzzHKwMcTBZFD4hymhydk6sU3nj7V0KorShn+kOFpxwEj
    SECRET_ACCESS_KEY: AgAhNcoW1GaO313xXlgB/4NZtA+czehl8HEMPwFDBsn+SZAzfbwx/aRVfbhhfcKfEevO/ICDTA4qYzVEQoKQdFnhzoUIp42Im2lgqViSugRic11Gwc0HnsRcQT+AYm6rREEkhwxp5zfBVc0RoxtrOkguV7MeJbEi67QphuDMMRN+8Y4e4EOlXqIHJt2JYoGb8nRGXIazkxqEHyB+uVlAqBdr4tmLuR534vJrsPyJ+4WjdJjA5zMj6uK1uKVYjR4gc7rUTDeHde4kmMHAT54ejlXoqYSM+iNIcQla3rK3oYQjOBGlb2Bf/R6+iwHhnaIh/Vbi6ChvYicfMYZeQc5yQ87qJYSETAQA6NCV+ERLq/rKljIlHiMnanuTDialUSUiowcH7+l/1SsMmESgLzfT5qt1o+uXL12piLqq7G8bY8lshh3gZHG8/J/V6cflVFzzuBgZcg4qKv7a1smgasvNFxlDepPIDKQaVkHqXClB9vlyZ1TUYW0qT8XPX05GUdmMbauXuSUy2lU7rRxjLTKRVTKNqMFyOYs+30SoKG/9aFdE++9dStdqI31Xoji29BBKK2DMhXuVmAOZnpas3fW3Intzabl9n84uv7hxOIk6pY3bdSZcIyphEi3umDYPbVmTDileNMnveI4NwNh16bdtC0qz+NMWoPEChTX0buZJv8FN4jI2vxLABLjLzjF5klpJilIsqYAZiMaD2lkVK2Vvnh8Ctr4FWchQ1M94qaVJeJsJIVtHqhWlMqMr46ZgDw==
  template:
    metadata:
      name: loki-s3-creds
      namespace: monitoring
