---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: discord-webhook
  namespace: monitoring
spec:
  encryptedData:
    DISCORD_WEBHOOK: AgB7VPqeuo+nH35IJaVBWGMGK+bsq0KRXjcRLeIgXWcXDcVneTBI7gRwOOwc9YGrHMyj30jKE10W0nrFp43vjwBg+rRUAfP1/QRycpxoPSP0N+pV+/w1bXKvCcT9vWw9hIpDFSATwjm1I+8j/oyBs0KSYEgvYsinwhyWLkQjGfq/QUFXw1vemukTVi9UNvjhrGbCGbJ8SEIj6Nkt7p3ZR582ZBnTlUFWDqMharXwdZwjGthe9RQq9F+sK3BWjsh/CR2Cxh5bhFQGTLW3G+itet9jxD5mydMTKVV6KgUxCbZfecpx1dTTEH+cc8Jwai6GvNQ0rkcXxLtGWpOydUrLDlNYkxf+vjpIAlmK5fK9GsI6KLWzubjmwQxmlF0+pz8d/6F5wH+k43+pIyU22tyVeLJ493OjKfCx2DMaDJIccsnrHOqeyJb4jO1fFUbyiy3ig0FXB4ndmj6KbJv+yx2SGYyF53iD1CCvP3OMVpXCIykmWk5S/hpfGVaqt2CXByjstX5LtMocDkC7p0lUDJ8PIxoXkIxp54Xb9GX4wwSkU8LXrSrfYsiEOAxKK0W44CT038GYjv8WOXjSzNE0eWds5i1jZ4KrBWkJazVvOBT5PZl0WtLVTKdiTldxaJwy0mR6zg/b8HfmmWWkzfqT04x0q6JoWcRwfC0dwY8P092z941S54aLTvfZT2UiXZsovB3ozxiQpFKoREzi3NG+GZ6Pfpx1iChVESCnEbjUpRQl92FKBZcm+pHMviUarYgP1majAmDwuFsRJJKlXQSGXd7tTNRcceXs+75n3MNmRhUiiVolro7usCV+k/ObeKwG/0zdjdOoETOwlrZ6saOuYNWhy9tkKSbJ8Mfy26yw
  template:
    metadata:
      name: discord-webhook
      namespace: monitoring
